on:
  push:
    branches:
      - master

name: 'Shellcheck pmbarrett314/config'

jobs:
  shellcheck:
    name: Shellcheck

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        ignore_paths: zsh sh/.include tests/bats tests/test_helper/bats-assert tests/test_helper/bats-support
        check_together: true
